#configure this discovery Server
eureka:
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    statusPageUrl: https://localhost:${server.port}/info
    healthCheckUrl: https://localhost:${server.port}/health
    homePageUrl: https://localhost:${server.port}
  client:
    register-with-eureka: false
    enabled=false:
    fetch-registry: false
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8111
#HTTP port
server:
  port: 8111

#  ssl:
#    enabled: true
#    key-store: classpath:exportwall-keystore.jks
#    key-store-password: myPassPhrase
#    key-alias: expertwall
#    key-store-provider: SUN
#    key-store-type: JKS
#    key-password: sunil45143


#  ssl:
#    enabled: true
#    key-store: classpath:eureka.jks
#    key-store-password: 123456
#    trust-store: classpath:eureka.jks
#    trust-store-password: 123456
#    key-alias: eureka
#    client-auth: need
#  ssl:
#    enabled: true
#    key-store: classpath:keyStore.p12
#    key-store-password: sunil45143
#    key-store-type: PKCS
#    key-password: sunil45143
#    trust-store: classpath:trustStore.jks
#    trust-store-password: sunil45143
#    trust-store-type: JKS


  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:nt-gateway.jks
    key-store-password: sunil45143
    key-alias: nt-ms
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:nt-ms.jks
    trust-store-password: sunil45143
    trust-store-type: JKS